### ISSUE TITLE
Analyze issues with 469 druids failing indexing

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/discovery-indexer#25]
https://gist.github.com/mejackreed/68755eb862f279f660b33d1028ca09f8

Per @mejackreed:

Seems that jobs are processing just fine the first time around, but will often get stuck in the mud after they fail multiple times. Most of the failures seem to be issues like `DiscoveryIndexer::Errors::MissingRDF` on the indexing side

Analysis of one object in prod shows an ETD with RELS-EXT as follows:

`<rdf:RDF xmlns:fedora="info:fedora/fedora-system:def/relations-external#" xmlns:fedora-model="info:fedora/fedora-system:def/model#" xmlns:hydra="http://projecthydra.org/ns/relations#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about="info:fedora/druid:bg468jw7546"></rdf:Description>
</rdf:RDF>`

However, in the -test environment this is missing altogether. Seems to be from a batch of bad data from 2012.

**Comment by blalbrit** [comment]
List of druids at: https://gist.github.com/mejackreed/68755eb862f279f660b33d1028ca09f8

**Comment by drh-stanford** [comment]
900 druids here (from stage) -- https://gist.github.com/drh-stanford/12b60cb177190759cfc460829a3d15d2

**Comment by lmcglohon** [comment]
closed by #26
